### ISSUE TITLE
Request to show my hash correlated to the btc_tx_id

### ISSUE THREAD

**Issue by pkankipati** [chainpoint/chainpoint-parse#3]
Hi:
I would like to see how I can correlate my hash to the btc_tx_id (ie op_return). I was able to use the parse to get my block height and btc_tx_id but when I went to the blockchain explorer or block cypher or other tools I was not able to see where my hash was in the transactions that got submitted.
Appreciate if you could enhance and provide the missing link, how my hash belongs in the OP_RETURN of a given tx.

thanks
pad

**Comment by grempe** [comment]
Hi @pkankipati 

To clarify, you won't ever directly see your original hash represented in an `OP_RETURN` value or in the Chainpoint Calendar blockchain. The values that are stored there represent a number of hashing operations as well as several aggregations into Merkle trees.  We only directly anchor a Merkle Root to a blockchain.

However, if you interest is more in the direction of being able to see the intermediate hashing results as part of the output of the `chainpoint-parse` lib that is something we can think about.  If we provided the ability to (optionally) output the intermediate results of all of the hashing operations that take place as steps in processing the proof, allowing you to additively see the hash resulting from each step, would that solve what you are after? This would perhaps be output as an Array of objects structured like:

```
[
...
{
  base: 1c2fa463dc2445cd1be277e3c7a755e4c12b31cbeea9337421dfef1e91df6cf3,
  left: 1c2fa463dc2445cd1be277e3c7a755e4c12b31cbeea9337421dfef1e91df6cf3,
  right: b1580f9354b15362614caaec83d7344a6aed04082d1e23783cd07cfcf36a8304
}
...
]
```

Where `base` represents the original hash, or the results of calculating the previous `l/r` operations and the `left` and `right` represent the next hash operation (prepend or append) that is to be done via concatenation which would result in the next base value?

This is something I think only advanced users would be interested in being able to calculate by hand to help understand the proof verification process and thus would not be output by default.

If this moves in the right direction we can look at how best to implement.

**Comment by pkankipati** [comment]
hmm.. that sounds like I've to recalculate/go backwards on every step to find my original hash with the btcTxId.
The problem is that a lot of my individual hashes are clubbed into mostly 1 btcTxId and it is difficult to see if my hash even got into that transaction as blockchain explorer or others doesn't provide a way to show that the original hash (of the data) within their transaction. 
The issue is reverse traversal, ie using the btcTxId to arrive to my original hash.. The above solution you mentioned does allow for re-verification traversal and might help me see the whole picture, so yes that would be helpful, a little roundabout way..

**Comment by grempe** [comment]
@pkankipati There is an important point to be made. It is not possible to "go backwards". All of the hashing done, and the Merkle roots created, are cryptographic *one-way* hashes. It is by design impossible to work backwards from any hash to the data that created it.

https://en.wikipedia.org/wiki/Cryptographic_hash_function

Also, no hashes are part of the "btcTxid", or transaction ID. Merkle roots from our Core are anchored to a bitcoin transaction in the `OP_RETURN` value. Our Chainpoint proofs calculate all the way up to the Merkle root of a specific Bitcoin block.

**Comment by pad-loyal** [comment]
I understand that hash is one way and cannot go back. I was just looking to see how we arrived at the final hash so that someone can perform the same hashes to ensure that the output matches what got put in the btcTxId.
That said, I think if you can provide the collection of all hashes from my original then it would help plus the algo..
So that programmatically I can do the same operation and ensure that the I get the same OP_RETURN value that goes into the btc.
thanks though.
